language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - TORNADO_VERSION=5.0 PYTEST_VERSION=3.6.4
    - TORNADO_VERSION=5.0 PYTEST_VERSION=4.0.0
    - TORNADO_VERSION=4.3 PYTEST_VERSION=2.8.6
    - TORNADO_VERSION=4.1 PYTEST_VERSION=2.8.6
    - TORNADO_VERSION=4.1 PYTEST_VERSION=2.7.0
    - TORNADO_VERSION=4.1 PYTEST_VERSION=2.6.4
install:
    - pip install -q tornado==$TORNADO_VERSION pytest==$PYTEST_VERSION
    - python setup.py install
    - pip install pytest-cov coveralls
matrix:
  exclude:
    - python: 3.5
      env: TORNADO_VERSION=4.1 PYTEST_VERSION=2.6.4
    - python: 3.5
      env: TORNADO_VERSION=4.1 PYTEST_VERSION=2.7.0
    - python: 3.6
      env: TORNADO_VERSION=4.1 PYTEST_VERSION=2.6.4
    - python: 3.6
      env: TORNADO_VERSION=4.1 PYTEST_VERSION=2.7.0
script:
    - py.test --strict

jobs:
  include:
    - stage: deploy
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: eugeniy
        password:
          secure: gmpsfekSDT9LuF3XkJK64myhQ6Xg8WyqI/0m5Gnnb+hSrCFGD8/dgtRdLEULuDkFPvL/FsoE2L6XcdKuqaKkqSM3kk4Min8hqGapcfe/OSOkCDaYSUBCXmV2dlbtMTAzHfo3zpueToUelZvblw9y3wXVFWkmr1mf47Q9kUPIgnU=
        on:
          tags: true
